name: Send email after webhook
on:
  webhook:
   
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: w00c0211.kasserver.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: TEST webhook
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: matthias.k@web.de
          from: matthias@k-l-e-i-n.de # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
